version: '3.8'

services:

    sftp-server:
        image: atmoz/sftp
        container_name: sftp-server
        volumes: 
            - ./sftp-server/data:/home/foo/upload/
        ports:
            - "2222:22"
        command: foo:pass:1001