# version: '3.8'

services:

    artemis:
        image: apache/activemq-artemis:2.37.0
        container_name: artemis
        environment: 
            - ARTEMIS_USER=admin
            - ARTEMIS_PASSWORD=admin
        ports:
            - 8161:8161
            - 61616:61616