version: '3.5'

services:

    postgres:
        image: postgres:12-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432