version: '3.8'

services:

    rest-proxy:
        image: confluentinc/cp-kafka-rest:6.1.1
        container_name: rest-proxy
        hostname: rest-proxy
        environment:
            - KAFKA_REST_HOST_NAME=rest-proxy
            - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
            - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092 
            - KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS=kafka:9092 
        ports:
            - 8082:8082