receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:
          allowed_origins:
            - "*"

  prometheus:
    config:
      scrape_configs:
        - job_name: 'BookingTripService'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['tripbooking:8080']  
        - job_name: 'BookingCarService'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['carbooking:8080']  
        - job_name: 'BookingHotelService'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['hotelbooking:8080']  
        - job_name: 'BookingFlightService'
          metrics_path: '/actuator/prometheus' 
          scrape_interval: 5s
          static_configs:
            - targets: ['flightbooking:8080']  

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true    # Add this to disable TLS

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]