version: '3.5'

services:

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.10.2
        # build: kibana                         #OpenDistro for ElasticSearch Kibana
        container_name: kibana
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
        ports:
            - 5601:5601