version: '3.5'

services:

    schema-registry:
        image: confluentinc/cp-schema-registry:6.1.1
        container_name: schema-registry
        environment: 
            - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
            - SCHEMA_REGISTRY_HOST_NAME=schema-registry
            - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
        ports:
            - 8081:8081