version: '3.8'

services:

    jaeger:
        image: jaegertracing/all-in-one:1.44
        container_name: jaeger
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 9411:9411
            - 16686:16686
            - 14268:14268
            - 14269:14269
            - 14250:14250