# version: '3.8'

services:

    jaeger:
        image:  jaegertracing/jaeger:2.3.0
        container_name: jaeger
        restart: always
        ports:
            - 16686:16686 
            - 4317:4317 
            - 4318:4318
            - 5778:5778
            - 9411:9411