version: '3.8'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector:1.44
      container_name: jaeger
      restart: on-failure
      command: 
        - "--collector.zipkin.host-port=9411"
        - "--kafka.producer.topic=jaeger"
        - "--kafka.producer.brokers=kafka:9092"
        - "--kafka.producer.encoding=json"
      environment: 
        - SPAN_STORAGE_TYPE=kafka
      ports:
        - "14250:14250"
        - "14269:14269" #Port for metrics in Prometheus format. Please use /metrics endpoint
        - "9411:9411"   #Port for receiving traces in Zipkin format
        
    jaeger-ingester:
      image: jaegertracing/jaeger-ingester:1.44
      container_name: jaeger-ingester
      restart: on-failure
      command:
        - "--es.server-urls=http://elasticsearch:9200"
        - "--kafka.consumer.brokers=kafka:9092"
        - "--kafka.consumer.topic=jaeger"
        - "--kafka.consumer.encoding=json"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
      ports:
        - "14270:14270"   #Port for metrics in Prometheus format. Please use /metrics endpoint
    
    jaeger-query:
      image: jaegertracing/jaeger-query:1.44
      container_name: jaeger-query
      restart: on-failure
      command:
        - "--es.server-urls=http://elasticsearch:9200"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
      ports:
        - "16686:16686"   #Port for UI
        - "16687:16687"   #Port for metrics in Prometheus format. Please use /metrics endpoint