version: '3.5'

services:

    openldap:
        image: bitnami/openldap:2
        container_name: openldap
        environment:
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=adminpassword
            - LDAP_USERS=user01,user02
            - LDAP_PASSWORDS=password1,password2
        ports:
            - 1389:1389
            - 1636:1636