version: '3.5'

services:

    prometheus:
        image: prom/prometheus:v2.27.1
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheusConfig.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090