version: '3.8'

services:

    prometheus:
        image: prom/prometheus:v2.37.7
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheusConfig.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090