# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://prometheus:9090
  # <string> database password, if used
  password: admin
  # <string> database user, if used
  user: admin
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: true
  # <string> basic auth username
  basicAuthUser: admin
  # <string> basic auth password
  basicAuthPassword: admin
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: Elasticsearch
  uid: 'logs-elastic'
  orgId: 1
  type: elasticsearch
  typeName: Elasticsearch
  access: proxy
  url: http://elasticsearch:9200
  password: 'elastic'
  user: 'elastic'
  database: "[filebeat-]YYYY.MM.DD"
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 70
    interval: Daily
    logLevelField: ''
    logMessageField: 'message'
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
  readOnly: false
  editable: true
- name: Jaeger
  type: jaeger
  uid: gdev-jaeger
  access: proxy
  url: http://jaeger:16686
  editable: true
  jsonData:
    tracesToLogsV2:
      customQuery: true
      datasourceUid: 'logs-elastic'
      spanStartTimeShift: '-2h'
      spanEndTimeShift: '2h'
      filterBySpanID: false
      filterByTraceID: true
      query: 'msg.traceid:"$${__span.traceId}"'
      tags: []