version: '3.8'

services:

    keycloak:
        # image: jboss/keycloak:12.0.4
        image: quay.io/keycloak/keycloak:12.0.4
        container_name: keycloak
        environment:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          KEYCLOAK_LOGLEVEL: INFO
        command: "-Dkeycloak.profile.feature.upload_scripts=enabled"
        ports:
          - 8080:8080
        volumes:
            - ./keycloak/providers/:/opt/jboss/keycloak/providers/