version: '3.8'

services:

    keycloak:
        ##--- KEYCLOAK 12.0.4 ---
        # image: quay.io/keycloak/keycloak:12.0.4
        # container_name: keycloak
        # environment:
        #   KEYCLOAK_USER: admin
        #   KEYCLOAK_PASSWORD: admin
        #   KEYCLOAK_LOGLEVEL: INFO
        # command: "-Dkeycloak.profile.feature.upload_scripts=enabled"
        # ports:
        #   - 8080:8080

        ###--- KEYCLOAK 19.0.2 ---
        image: quay.io/keycloak/keycloak:19.0.2
        container_name: keycloak
        environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KEYCLOAK_LOGLEVEL: INFO
        command: "-Dkeycloak.profile.feature.upload_scripts=enabled start-dev"
        ports:
          - 8080:8080