version: '3.8'

services:

  traefik:
    image: traefik:2.5
    container_name: traefik
    command:
      # - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 8080:80
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`localhost`) # Specify your hostname instead of localhost if needed
      - traefik.http.routers.whoami.entrypoints=web