version: '3.5'

services:

    grafana:
        image: grafana/grafana:7.5.7   
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            # Install plugins
            - GF_INSTALL_PLUGINS=vonage-status-panel,jdbranham-diagram-panel,agenty-flowcharting-panel,yesoreyeram-boomtable-panel
        ports:
            - 3000:3000
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always