version: '3'

services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    ports:
      - "8080:8080"
  kc-dev-data:
    image: stn1slv/keycloak-dev-data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_PORT=8080