version: '3.5'

volumes:
  maven_data:
    driver: local

services:
    tripbooking:
        build: TripBooking
        container_name: trip-booking-app
        ports:
            - 8080:8080
        volumes:
            - maven_data:/root/.m2
    carbooking:
        build: CarBooking
        container_name: car-booking-app
        ports:
            - 8081:8080
        volumes:
            - maven_data:/root/.m2
    flightbooking:
        build: FlightBooking
        container_name: flight-booking-app
        ports:
            - 8082:8080
        volumes:
            - maven_data:/root/.m2
    hotelbooking:
        build: HotelBooking
        container_name: hotel-booking-app
        ports:
            - 8083:8080
        volumes:
            - maven_data:/root/.m2