# version: '3.8'

services:
    kafka:
        image: bitnami/kafka:4.0
        container_name: kafka
        restart: always
        environment:
            KAFKA_CFG_NODE_ID: 0
            KAFKA_CFG_PROCESS_ROLES: broker,controller
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CLIENT_USERS: user
            KAFKA_CLIENT_PASSWORDS: password
        ports:
            - 9092:9092
            - 9094:9094 #use this port to connect from outside the container
