version: '3'

volumes:
  maven_data:
    driver: local

services:
    tripbooking:
        build: demo-apps/TripBooking
        container_name: trip-booking-app
        ports:
            - 8080:8080
        volumes:
            - maven_data:/root/.m2
    carbooking:
        build: demo-apps/CarBooking
        container_name: car-booking-app
        ports:
            - 8081:8080
        volumes:
            - maven_data:/root/.m2
    flightbooking:
        build: demo-apps/FlightBooking
        container_name: flight-booking-app
        ports:
            - 8082:8080
        volumes:
            - maven_data:/root/.m2
    hotelbooking:
        build: demo-apps/HotelBooking
        container_name: hotel-booking-app
        ports:
            - 8083:8080
        volumes:
            - maven_data:/root/.m2
    filebeat:
        image: docker.elastic.co/beats/filebeat-oss:7.10.2
        container_name: filebeat
        user: root
        volumes: 
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
        command: filebeat -e -strict.perms=false