version: '3'

services:
    grafana:
        image: grafana/grafana:7.5.7   
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        # volumes:
        #     - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always
    prometheus:
        image: prom/prometheus:v2.27.1
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheusConfig.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    zipkin:
        image: openzipkin/zipkin:2.23
        container_name: zipkin
        environment: 
            - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/discover?_a=(index:'filebeat-*',query:(language:lucene,query:'{traceId}'))
        ports:
            - 9411:9411
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        # image: amazon/opendistro-for-elasticsearch:1.13.2
        container_name: elasticsearch
        environment:
            - node.name=es01
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # - opendistro_security.disabled=true #OpenDistro: disable security for PoC purposes
            # - DISABLE_INSTALL_DEMO_CONFIG=true  #OpenDistro: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
                hard: 65536
        ports:
            - 9200:9200
            - 9300:9300
            # - 9600:9600                       #OpenDistro: performance profiler port
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.10.2
        # build: kibana                         #OpenDistro for ElasticSearch Kibana
        container_name: kibana
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
        ports:
            - 5601:5601