version: '3.8'

services:
    schema-registry:
        image: apicurio/apicurio-registry-mem:2.6.2.Final
        container_name: schema-registry
        environment:
            ###--- COMMON CONFIG ---
            - AUTH_ENABLED=true
            - KEYCLOAK_URL=http://keycloak:8080/
            # - KEYCLOAK_URL=http://keycloak:8080/auth #for old keycloak servers
            - KEYCLOAK_REALM=registry
            - KEYCLOAK_API_CLIENT_ID=registry-api
            - KEYCLOAK_UI_CLIENT_ID=apicurio-registry
            # - REGISTRY_LOG_LEVEL=INFO

            ###--- HTTP BASIC AUTH ---
            # - REGISTRY_AUTH_CLIENT_SECRET=registry-api-secret
            # - REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED=true
            # - ROLE_BASED_AUTHZ_ENABLED=true
            # # - ROLE_BASED_AUTHZ_SOURCE=token
            
            ###--- AOUTH2 AUTH ---
            - CLIENT_CREDENTIALS_BASIC_AUTH_ENABLED=false
            - REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED=true
            - ROLE_BASED_AUTHZ_ENABLED=true
            - ROLE_BASED_AUTHZ_SOURCE=token
            - OWNER_ONLY_AUTHZ_ENABLED=true
            - REGISTRY_UI_CONFIG_AUTH_TYPE=none
            # - REGISTRY_UI_FEATURES_READONLY=true
            # - QUARKUS_KEYCLOAK_POLICY_ENFORCER_ENABLE=true
            ### Configuration params: https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/getting-started/assembly-configuring-the-registry.html#all-registry-configs_registry
        ports:
            - 8180:8080
